codecov:
  require_ci_to_pass: true
  token: # Optional: Add your Codecov token here for private repos
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
        branches:
          - main
          - master
        if_not_found: success
        if_ci_failed: error
      eslint-plugin-fsd:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
      web:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
      eslint-plugin-fsd:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
      web:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  show_carryforward_flags: true

github_checks:
  annotations: true
  annotate:
    default:
      file: "all"
      only_changed_files: false

flags:
  eslint-plugin-fsd:
    paths:
      - packages/eslint-plugin-fsd/src
    carryforward: true
    status:
      project:
        target: 70%
        threshold: 2%
        base: auto
        branches:
          - main
          - master
        if_not_found: success
        if_ci_failed: error
      patch:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error
  web:
    paths:
      - packages/web/src
    carryforward: true
    status:
      project:
        target: 70%
        threshold: 2%
        base: auto
        branches:
          - main
          - master
        if_not_found: success
        if_ci_failed: error
      patch:
        target: 70%
        threshold: 2%
        base: auto
        if_not_found: success
        if_ci_failed: error

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  - "**/out/**"
  - "**/coverage/**"
  - "**/*.d.ts"
  - "**/types.ts"
  - "**/index.ts"
  - "**/vitest.config.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/playwright-report/**"
  - "**/test-results/**"
  - "**/.cache/**"
